"""auto-generated migration

Revision ID: 65c950e4f616
Revises: 
Create Date: 2025-06-02 01:07:46.083024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c950e4f616'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('initial_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('useful_life_years', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    # ### end Alembic commands ###
