"""auto-generated migration

Revision ID: de04f0910b7b
Revises: 65c950e4f616
Create Date: 2025-06-02 01:18:01.483289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de04f0910b7b'
down_revision = '65c950e4f616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###
